// Cohort — dados de referência sobre concursos militares e vestibulares
// tradicionais. Conteúdo curado manualmente (não gerado por IA, pra evitar
// erro em informação sensível como idade/escolaridade exigida). Datas e
// número de vagas mudam a cada edital - por isso a tela sempre reforça
// pra confirmar no edital/manual oficial vigente.

export const EXAMS = [
  // ============================================================
  // Militares
  // ============================================================
  {
    id: "espcex",
    categoria: "militar",
    sigla: "EsPCEx",
    nome: "Escola Preparatória de Cadetes do Exército",
    grupo: "exercito",
    nivel: "medio",
    carreira: "Oficial combatente do Exército",
    cidade: "Campinas (SP)",
    idade: "17 a 22 anos completos até 31/12 do ano da matrícula",
    escolaridade: "Ensino médio completo até a matrícula",
    materias: ["Português", "Matemática", "Física", "Química", "Inglês", "Geografia", "História", "Redação"],
    etapas: [
      "Exame Intelectual (prova objetiva, 2 dias) + redação",
      "Inspeção de saúde",
      "Teste de Aptidão Física (TAF)",
      "Investigação social e validação documental",
    ],
    vagasRecentes: "440 vagas (concurso 2027)",
    datasRecentes: "Inscrições: abr–jun/2026 · Provas: 12 e 13/09/2026 · Matrícula prevista: fev/2027",
  },
  {
    id: "afa",
    categoria: "militar",
    sigla: "AFA",
    nome: "Academia da Força Aérea",
    grupo: "aeronautica",
    nivel: "medio",
    carreira: "Oficial da Aeronáutica (aviador, intendente ou infantaria)",
    cidade: "Pirassununga (SP)",
    idade: "17 a 22 anos completos até 31/12 do ano da matrícula",
    escolaridade: "Ensino médio completo",
    materias: ["Português", "Matemática", "Física", "Inglês", "Redação"],
    etapas: [
      "Provas escritas (objetiva + redação)",
      "Inspeção de saúde (INSPSAU)",
      "Exame de aptidão psicológica (EAP)",
      "Teste de condicionamento físico (TACF)",
      "Investigação social",
    ],
    vagasRecentes: "55 vagas (concurso 2027)",
    datasRecentes: "Inscrições: 06 a 27/04/2026 · Prova: 05/07/2026 · Matrícula prevista: jan/2027",
  },
  {
    id: "en",
    categoria: "militar",
    sigla: "EN",
    nome: "Escola Naval",
    grupo: "marinha",
    nivel: "medio",
    carreira: "Oficial da Marinha (Corpo da Armada, Fuzileiros Navais ou Intendência)",
    cidade: "Rio de Janeiro (RJ)",
    idade: "Não pode ser casado(a) ou ter filhos na inscrição nem até a matrícula",
    escolaridade: "Ensino médio completo",
    materias: ["Português", "Matemática", "Física", "Inglês", "Redação"],
    etapas: [
      "Prova escrita objetiva (2 dias) + redação dissertativa",
      "Avaliação psicológica",
      "Inspeção de saúde",
      "Teste de natação (50m) e Teste de Aptidão Física",
    ],
    vagasRecentes: "49 vagas (concurso 2027) — 37 para homens, 12 para mulheres",
    datasRecentes: "Inscrições: 30/04 a 13/05/2026 · Provas: 29 e 30/08/2026 · Início do curso: fev/2027",
  },
  {
    id: "eear",
    categoria: "militar",
    sigla: "EEAr",
    nome: "Escola de Especialistas de Aeronáutica",
    grupo: "aeronautica",
    nivel: "medio",
    carreira: "Praça — Curso de Formação de Sargentos (CFS) da Aeronáutica",
    cidade: "Guaratinguetá (SP)",
    idade: "17 a 24/25 anos (varia por edital, confirme o limite exato)",
    escolaridade: "Ensino médio completo",
    materias: ["Português", "Inglês", "Matemática", "Física"],
    etapas: [
      "Prova escrita objetiva",
      "Inspeção de saúde",
      "Exame psicológico",
      "Teste de Avaliação do Condicionamento Físico (TACF)",
      "Validação documental",
    ],
    vagasRecentes: "235 vagas (CFS 2/2027)",
    datasRecentes: "Inscrições: 11/06 a 02/07/2026 · Prova: 22/11/2026",
  },
  {
    id: "essa",
    categoria: "militar",
    sigla: "EsSA",
    nome: "Escola de Sargentos das Armas",
    grupo: "exercito",
    nivel: "medio",
    carreira: "Praça — Curso de Formação e Graduação de Sargentos (áreas Geral, Música e Saúde)",
    cidade: "Três Corações (MG)",
    idade: "17 a 24 anos (área Geral) · 17 a 26 anos (Música e Saúde)",
    escolaridade: "Ensino médio completo",
    materias: ["Português", "Matemática", "História e Geografia do Brasil", "Inglês", "Redação (exceto área Geral)"],
    etapas: [
      "Exame Intelectual (objetiva)",
      "Redação (áreas Música e Saúde)",
      "Exame de Habilitação Musical (só área Música)",
      "Inspeção de saúde",
      "Teste de Aptidão Física",
    ],
    vagasRecentes: "1.100 vagas (concurso 2026, matrícula 2027)",
    datasRecentes: "Inscrições: 30/03 a 18/05/2026 · Prova: 26/07/2026",
  },
  {
    id: "ime",
    categoria: "militar",
    sigla: "IME",
    nome: "Instituto Militar de Engenharia",
    grupo: "exercito",
    nivel: "superior",
    carreira: "Engenharia militar (carreira Ativa) ou civil (carreira Reserva)",
    cidade: "Rio de Janeiro (RJ) — Praia Vermelha",
    idade: "Ativa: 16 a 22 anos até 31/12 do ano da matrícula · Reserva: até 21 anos no ano anterior à matrícula",
    escolaridade: "Ensino médio completo (ou concluindo)",
    materias: ["Matemática", "Física", "Química", "Português", "Inglês"],
    etapas: [
      "1ª fase: prova objetiva (classificatória)",
      "2ª fase: discursivas de Matemática, Física e Química",
      "2ª fase: Português (com redação) e Inglês",
    ],
    vagasRecentes: "100 vagas (concurso 2027) — 70 Ativa, 30 Reserva",
    datasRecentes: "Inscrições: 27/05 a 08/07/2026 · 1ª fase: 20/09/2026 · 2ª fase: 26 a 29/10/2026 · Matrícula: fev/2027",
  },
  {
    id: "ita",
    categoria: "militar",
    sigla: "ITA",
    nome: "Instituto Tecnológico de Aeronáutica",
    grupo: "aeronautica",
    nivel: "superior",
    carreira: "Engenharia — oficial engenheiro da Aeronáutica (Ativa ou Reserva)",
    cidade: "São José dos Campos (SP)",
    idade: "Não completar 25 anos até 31/12 do ano da matrícula · solteiro(a), brasileiro(a) nato(a)",
    escolaridade: "Ensino médio completo",
    materias: ["Matemática", "Física", "Química", "Inglês", "Português (com redação)"],
    etapas: [
      "1ª fase: prova objetiva de Matemática, Física, Química e Inglês",
      "2ª fase: discursivas de Matemática, Física, Química, Português e Redação",
      "3ª fase: Inspeção de Saúde",
    ],
    vagasRecentes: "200 vagas (concurso 2027) — 140 ampla concorrência + reservas",
    datasRecentes: "Inscrições: 02/06 a 12/07/2026 · 1ª fase: 27/09/2026 · 2ª fase: 20 a 23/10/2026 · Matrícula: fev/2027",
  },

  // ============================================================
  // Vestibulares tradicionais
  // ============================================================
  {
    id: "fuvest",
    categoria: "tradicional",
    sigla: "FUVEST",
    nome: "Vestibular da USP (Fundação Universitária para o Vestibular)",
    grupo: "SP",
    nivel: "superior",
    carreira: "Ingresso em mais de 180 cursos de graduação da USP",
    cidade: "São Paulo e outras cidades do estado de SP",
    idade: "Sem limite de idade",
    escolaridade: "Ensino médio completo (candidatos concluindo também podem se inscrever)",
    materias: ["Português", "Matemática", "Física", "Química", "Biologia", "História", "Geografia", "Inglês", "Redação"],
    etapas: [
      "1ª fase: prova objetiva multidisciplinar (classificatória para a 2ª fase)",
      "2ª fase: provas discursivas + redação, específicas por curso",
      "Provas de competências específicas (Música, Artes Cênicas e Artes Visuais, quando aplicável)",
    ],
    vagasRecentes: "Milhares de vagas em mais de 180 cursos (vestibular 2027)",
    datasRecentes: "Inscrições: 17/08 a 09/10/2026 · 1ª fase: 01/11/2026 · 2ª fase: 06 e 07/12/2026 · 1ª chamada: 26/01/2027",
  },
  {
    id: "uerj",
    categoria: "tradicional",
    sigla: "UERJ",
    nome: "Vestibular Estadual da UERJ",
    grupo: "RJ",
    nivel: "superior",
    carreira: "Ingresso nos cursos de graduação da Universidade do Estado do Rio de Janeiro",
    cidade: "Rio de Janeiro (RJ)",
    idade: "Sem limite de idade",
    escolaridade: "Ensino médio completo (candidatos concluindo também podem se inscrever)",
    materias: ["Linguagens", "Matemática", "Ciências da Natureza", "Ciências Humanas", "Redação", "2 provas específicas do curso"],
    etapas: [
      "Exame de Qualificação (1ª ou 2ª edição) - objetiva, 60 questões",
      "Exame Discursivo - redação + 2 provas específicas do curso escolhido",
    ],
    vagasRecentes: "Vagas distribuídas entre os diversos cursos de graduação (vestibular 2027)",
    datasRecentes: "1º Exame de Qualificação: inscrições 16/04 a 06/05/2026, prova 07/06/2026 · 2º Exame de Qualificação: inscrições 17/07 a 07/08/2026, prova 06/09/2026 · Exame Discursivo: data a divulgar",
  },
  {
    id: "ufu",
    categoria: "tradicional",
    sigla: "UFU",
    nome: "Concurso Seletivo Vestibular da Universidade Federal de Uberlândia",
    grupo: "MG",
    nivel: "superior",
    carreira: "Ingresso nos cursos de graduação da UFU (campi de Uberlândia, Ituiutaba, Patos de Minas e Monte Carmelo)",
    cidade: "Uberlândia (MG) e outras cidades de MG, GO e SP",
    idade: "Sem limite de idade",
    escolaridade: "Ensino médio completo (candidatos concluindo também podem se inscrever)",
    materias: ["Português", "Literatura", "Língua Estrangeira", "Matemática", "Física", "Química", "Biologia", "História", "Geografia", "Redação"],
    etapas: [
      "1ª fase: prova objetiva multidisciplinar (65 questões, 5h30)",
      "2ª fase: redação (aplicada no mesmo dia da 1ª fase)",
    ],
    vagasRecentes: "1.729 vagas em 51 cursos (concurso 2026-2)",
    datasRecentes: "A UFU costuma abrir edital 2x por ano - confira o cronograma vigente no Portal de Seleção da UFU",
  },
  {
    id: "upe",
    categoria: "tradicional",
    sigla: "UPE (SSA)",
    nome: "Sistema Seriado de Avaliação da Universidade de Pernambuco",
    grupo: "PE",
    nivel: "superior",
    carreira: "Ingresso nos cursos de graduação da UPE (vestibular seriado ao longo do ensino médio)",
    cidade: "Recife e outros polos de PE",
    idade: "Voltado a quem cursa o ensino médio regularmente durante o SSA",
    escolaridade: "Cursando ou tendo concluído o ensino médio (SSA1 ao SSA3, um por ano do EM)",
    materias: ["Linguagens e suas Tecnologias", "Ciências Humanas e Sociais Aplicadas", "Matemática e suas Tecnologias", "Ciências da Natureza e suas Tecnologias", "Redação"],
    etapas: [
      "SSA1 (1º ano do EM) e SSA2 (2º ano do EM) - contam pra composição da nota, mas não classificam sozinhos",
      "SSA3 (3º ano do EM) - decide a classificação final",
      "Cada etapa: 2 dias de prova objetiva + redação",
    ],
    vagasRecentes: "3.710 vagas (1.855 pelo SSA + 1.855 pelo SiSU) em 61 cursos, 17 campi (SSA 2027)",
    datasRecentes: "Inscrições: 08/06 a 10/07/2026 · SSA3: 01 e 02/11/2026 · SSA1 e SSA2: 06 e 13/12/2026",
  },
];

export const MILITARY_GROUP_LABELS = {
  exercito: "Exército",
  marinha: "Marinha",
  aeronautica: "Aeronáutica",
};
